openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
paths:
  /auth:
    get:
      parameters:
        - name: ent
          in: query
          required: true
          schema:
            type: string
            enum: ['toutatice']
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  cookies:
                    type: object
        '400':
          description: Missing or unsupported parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string